# Generated by Django 5.2.3 on 2025-12-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Action", "Action"),
                    ("Comedy", "Comedy"),
                    ("Drama", "Drama"),
                    ("Romance", "Romance"),
                    ("Thriller", "Thriller"),
                ],
                default="Action",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="language",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("Hindi", "Hindi"),
                    ("Tamil", "Tamil"),
                    ("Telugu", "Telugu"),
                ],
                default="Action",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
