# Generated by Django 5.2.3 on 2025-12-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_genre_movie_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(blank=True, help_text="Paste YouTube trailer link"),
        ),
    ]
